export const REBORN_MOVE_LEGALITY_BASE = {
  generation: 7,
  baseGames: "USUM",
  transferMovesAvailableByDefault: false,
};

export const REBORN_TMX_MOVES = ["Fly", "Surf", "Waterfall"];

export const REBORN_PROMOTED_TM_MOVES = [
  "Power-Up Punch",
  "Struggle Bug",
  "Secret Power",
];

export const REBORN_LEVEL_ONE_MOVE_OVERRIDES = {
  bulbasaur: ["Weather Ball"],
  ivysaur: ["Weather Ball"],
  venusaur: ["Weather Ball"],
  charmander: ["Quick Attack", "Howl"],
  charmeleon: ["Quick Attack", "Howl"],
  charizard: ["Quick Attack", "Howl"],
  squirtle: ["Follow Me"],
  pichu: ["Follow Me", "Teeter Dance"],
  pikachu: ["Follow Me", "Teeter Dance", "Extreme Speed", "Sing", "Yawn"],
  raichu: ["Follow Me", "Teeter Dance", "Extreme Speed", "Sing", "Yawn"],
  jigglypuff: ["Tickle"],
  wigglytuff: ["Tickle"],
  oddish: ["Leech Seed"],
  gloom: ["Leech Seed"],
  vileplume: ["Leech Seed"],
  bellossom: ["Leech Seed"],
  meowth: ["Sing"],
  persian: ["Sing"],
  farfetchd: ["Wish", "Yawn"],
  drowzee: ["Wish", "Belly Drum"],
  hypno: ["Wish", "Belly Drum"],
  exeggcute: ["Wish"],
  exeggutor: ["Wish"],
  lickitung: ["Wish", "Heal Bell"],
  lickilicky: ["Wish", "Heal Bell"],
  chansey: ["Wish"],
  blissey: ["Wish"],
  happiny: ["Wish"],
  kangaskhan: ["Wish", "Yawn"],
  eevee: ["Sing"],
  vaporeon: ["Sing"],
  jolteon: ["Sing"],
  flareon: ["Sing"],
  espeon: ["Sing"],
  umbreon: ["Sing"],
  leafeon: ["Sing"],
  glaceon: ["Sing"],
  sylveon: ["Sing"],
  dragonite: ["Barrier", "Extreme Speed"],
  mewtwo: ["Electro Ball", "Hurricane"],
  wynaut: ["Tickle"],
  wobbuffet: ["Tickle"],
  raikou: ["Zap Cannon", "Weather Ball", "Aura Sphere", "Extreme Speed"],
  entei: ["Flare Blitz", "Crush Claw", "Howl", "Extreme Speed"],
  suicune: ["Air Slash", "Aqua Ring", "Extreme Speed"],
  lugia: ["Hurricane", "Defog", "Tailwind", "Skill Swap"],
  hooh: ["Burn Up"],
  celebi: ["Nasty Plot"],
  taillow: ["Feather Dance"],
  swellow: ["Feather Dance"],
  sableye: ["Tickle", "Octazooka"],
  spinda: ["Sing"],
  cacnea: ["Encore"],
  cacturne: ["Encore"],
  banette: ["Cotton Guard"],
  absol: ["Wish"],
  bagon: ["Wish"],
  shelgon: ["Wish"],
  salamence: ["Wish"],
  metang: ["Refresh"],
  metagross: ["Refresh"],
  rayquaza: ["Dragon Ascent", "V-create"],
  jirachi: [
    "Draco Meteor",
    "Moonblast",
    "Heart Stamp",
    "Meteor Mash",
    "Play Rough",
    "Follow Me",
  ],
  deoxys: ["Meteor Mash", "Nasty Plot", "Detect", "Zap Cannon", "Extreme Speed"],
  piplup: ["Sing"],
  prinplup: ["Sing"],
  empoleon: ["Sing"],
  heatran: ["Eruption"],
  darkrai: ["Phantom Force", "Spacial Rend", "Roar of Time"],
  arceus: ["Shadow Force", "Roar of Time", "Spacial Rend"],
  victini: [
    "V-create",
    "Fusion Flare",
    "Fusion Bolt",
    "Bolt Strike",
    "Blue Flare",
    "Glaciate",
  ],
  snivy: ["Aromatherapy"],
  servine: ["Aromatherapy"],
  serperior: ["Aromatherapy"],
  gothorita: ["Imprison"],
  gothitelle: ["Imprison"],
  reshiram: ["Mist"],
  zekrom: ["Haze"],
  keldeo: ["Secret Sword"],
  meloetta: ["Relic Song"],
  genesect: ["Blaze Kick", "Extreme Speed", "Shift Gear"],
  zygarde: [
    "Dragon Dance",
    "Extreme Speed",
    "Thousand Waves",
    "Thousand Arrows",
    "Core Enforcer",
  ],
  zygarde10: [
    "Dragon Dance",
    "Extreme Speed",
    "Thousand Waves",
    "Thousand Arrows",
    "Core Enforcer",
  ],
  zygardecomplete: [
    "Dragon Dance",
    "Extreme Speed",
    "Thousand Waves",
    "Thousand Arrows",
    "Core Enforcer",
  ],
};

export const REBORN_TUTOR_MOVE_OVERRIDES = {
  silvally: ["Fire Pledge", "Water Pledge"],
  silvallybug: ["Fire Pledge", "Water Pledge"],
  silvallydark: ["Fire Pledge", "Water Pledge"],
  silvallydragon: ["Fire Pledge", "Water Pledge"],
  silvallyelectric: ["Fire Pledge", "Water Pledge"],
  silvallyfairy: ["Fire Pledge", "Water Pledge"],
  silvallyfighting: ["Fire Pledge", "Water Pledge"],
  silvallyfire: ["Fire Pledge", "Water Pledge"],
  silvallyflying: ["Fire Pledge", "Water Pledge"],
  silvallyghost: ["Fire Pledge", "Water Pledge"],
  silvallygrass: ["Fire Pledge", "Water Pledge"],
  silvallyground: ["Fire Pledge", "Water Pledge"],
  silvallyice: ["Fire Pledge", "Water Pledge"],
  silvallypoison: ["Fire Pledge", "Water Pledge"],
  silvallypsychic: ["Fire Pledge", "Water Pledge"],
  silvallyrock: ["Fire Pledge", "Water Pledge"],
  silvallysteel: ["Fire Pledge", "Water Pledge"],
  silvallywater: ["Fire Pledge", "Water Pledge"],
};

export const REBORN_TM_MOVE_OVERRIDES = {
  gengar: ["Sludge Wave"],
};

export const REBORN_TMX_MOVE_OVERRIDES = {
  pikachu: ["Fly", "Surf"],
  raichu: ["Fly", "Surf"],
};

export const REBORN_TM_REPLACEMENTS = {
  Fly: "Power-Up Punch",
  Surf: "Struggle Bug",
  Waterfall: "Secret Power",
};

export const REBORN_PROGRESSION_NOTES = [
  "Move legality is based on USUM learnsets, with Reborn-specific exceptions.",
  "Generic transfer moves are unavailable.",
  "Fly, Surf, and Waterfall are TMX moves in Reborn, not ordinary TMs.",
  "Power-Up Punch, Struggle Bug, and Secret Power are promoted to TMs.",
  "Promoted TMs are legal for Pokémon that learn the move elsewhere or had it as a Gen 6 transfer move.",
  "Reborn extra move-relearner moves are encoded from the wiki Mechanics learnset changes.",
];
